"""Initial migration

Revision ID: bc92916f13c3
Revises: 
Create Date: 2026-01-15 05:03:21.859574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc92916f13c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('custom_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_created_at', 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index('ix_companies_owner_id', 'companies', ['owner_id'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_templates_created_by', 'email_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=False)
    op.create_table('file_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_attachments_s3_key'), 'file_attachments', ['s3_key'], unique=True)
    op.create_table('pipelines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipelines_is_active', 'pipelines', ['is_active'], unique=False)
    op.create_index('ix_pipelines_is_default', 'pipelines', ['is_default'], unique=False)
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.Enum('LINKEDIN', 'TWITTER', 'FACEBOOK', name='socialplatform'), nullable=False),
    sa.Column('platform_user_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('platform_username', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('profile_image_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'TOKEN_EXPIRED', 'ERROR', name='accountstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('platform_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_accounts_owner_id', 'social_accounts', ['owner_id'], unique=False)
    op.create_index('ix_social_accounts_platform', 'social_accounts', ['platform'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('LEAD', 'PROSPECT', 'CUSTOMER', 'CHURNED', 'OTHER', name='contactstatus'), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('custom_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_company_id', 'contacts', ['company_id'], unique=False)
    op.create_index('ix_contacts_created_at', 'contacts', ['created_at'], unique=False)
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_first_name'), 'contacts', ['first_name'], unique=False)
    op.create_index('ix_contacts_full_name', 'contacts', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_contacts_last_name'), 'contacts', ['last_name'], unique=False)
    op.create_index('ix_contacts_owner_id', 'contacts', ['owner_id'], unique=False)
    op.create_index('ix_contacts_status', 'contacts', ['status'], unique=False)
    op.create_table('email_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'PAUSED', 'CANCELLED', name='campaignstatus'), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('track_opens', sa.Boolean(), nullable=False),
    sa.Column('track_clicks', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_campaigns_created_by', 'email_campaigns', ['created_by'], unique=False)
    op.create_index(op.f('ix_email_campaigns_name'), 'email_campaigns', ['name'], unique=False)
    op.create_index('ix_email_campaigns_scheduled_at', 'email_campaigns', ['scheduled_at'], unique=False)
    op.create_index('ix_email_campaigns_status', 'email_campaigns', ['status'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_stages_order', 'pipeline_stages', ['order'], unique=False)
    op.create_index('ix_pipeline_stages_pipeline_id', 'pipeline_stages', ['pipeline_id'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('link_title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('link_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'QUEUED', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'CANCELLED', name='poststatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('platform_post_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('platform_post_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_posts_account_id', 'social_posts', ['account_id'], unique=False)
    op.create_index('ix_social_posts_scheduled_at', 'social_posts', ['scheduled_at'], unique=False)
    op.create_index('ix_social_posts_status', 'social_posts', ['status'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Numeric(scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('actual_close_date', sa.Date(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lost_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('custom_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deals_company_id', 'deals', ['company_id'], unique=False)
    op.create_index('ix_deals_contact_id', 'deals', ['contact_id'], unique=False)
    op.create_index('ix_deals_created_at', 'deals', ['created_at'], unique=False)
    op.create_index('ix_deals_expected_close_date', 'deals', ['expected_close_date'], unique=False)
    op.create_index(op.f('ix_deals_name'), 'deals', ['name'], unique=False)
    op.create_index('ix_deals_owner_id', 'deals', ['owner_id'], unique=False)
    op.create_index('ix_deals_pipeline_id', 'deals', ['pipeline_id'], unique=False)
    op.create_index('ix_deals_stage_id', 'deals', ['stage_id'], unique=False)
    op.create_table('email_campaign_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('opened_count', sa.Integer(), nullable=False),
    sa.Column('clicked_count', sa.Integer(), nullable=False),
    sa.Column('bounced_count', sa.Integer(), nullable=False),
    sa.Column('complained_count', sa.Integer(), nullable=False),
    sa.Column('unsubscribed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('unique_opens', sa.Integer(), nullable=False),
    sa.Column('unique_clicks', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_index('ix_email_campaign_metrics_campaign_id', 'email_campaign_metrics', ['campaign_id'], unique=False)
    op.create_table('email_recipients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('personalization_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'OPENED', 'CLICKED', 'BOUNCED', 'COMPLAINED', 'UNSUBSCRIBED', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('bounced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_recipients_campaign_id', 'email_recipients', ['campaign_id'], unique=False)
    op.create_index('ix_email_recipients_contact_id', 'email_recipients', ['contact_id'], unique=False)
    op.create_index('ix_email_recipients_email', 'email_recipients', ['email'], unique=False)
    op.create_index('ix_email_recipients_status', 'email_recipients', ['status'], unique=False)
    op.create_table('social_media_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'GIF', 'LINK', name='mediatype'), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('platform_media_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_media_attachments_post_id', 'social_media_attachments', ['post_id'], unique=False)
    op.create_table('social_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('LINKEDIN', 'TWITTER', 'FACEBOOK', name='socialplatform'), nullable=False),
    sa.Column('platform_message_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('message_type', sa.Enum('DIRECT_MESSAGE', 'MENTION', 'COMMENT', 'REPLY', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_platform_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('sender_username', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('sender_display_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('sender_profile_image', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'RESPONDED', 'ARCHIVED', name='messagestatus'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('platform_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_message_id')
    )
    op.create_index('ix_social_messages_account_id', 'social_messages', ['account_id'], unique=False)
    op.create_index('ix_social_messages_message_type', 'social_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_social_messages_platform'), 'social_messages', ['platform'], unique=False)
    op.create_index('ix_social_messages_received_at', 'social_messages', ['received_at'], unique=False)
    op.create_index('ix_social_messages_status', 'social_messages', ['status'], unique=False)
    op.create_index('ix_social_messages_thread_id', 'social_messages', ['thread_id'], unique=False)
    op.create_table('social_post_analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('video_views', sa.Integer(), nullable=False),
    sa.Column('video_completion_rate', sa.Float(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.Column('platform_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index('ix_social_post_analytics_post_id', 'social_post_analytics', ['post_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('CALL', 'EMAIL', 'MEETING', 'NOTE', 'TASK', 'OTHER', name='activitytype'), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('custom_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_activity_date', 'activities', ['activity_date'], unique=False)
    op.create_index('ix_activities_company_id', 'activities', ['company_id'], unique=False)
    op.create_index('ix_activities_contact_id', 'activities', ['contact_id'], unique=False)
    op.create_index('ix_activities_created_at', 'activities', ['created_at'], unique=False)
    op.create_index('ix_activities_deal_id', 'activities', ['deal_id'], unique=False)
    op.create_index('ix_activities_owner_id', 'activities', ['owner_id'], unique=False)
    op.create_index(op.f('ix_activities_subject'), 'activities', ['subject'], unique=False)
    op.create_index('ix_activities_type', 'activities', ['type'], unique=False)
    op.create_table('deal_stage_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage_id', sa.Uuid(), nullable=True),
    sa.Column('to_stage_id', sa.Uuid(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['from_stage_id'], ['pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deal_stage_history_deal_id', 'deal_stage_history', ['deal_id'], unique=False)
    op.create_index('ix_deal_stage_history_entered_at', 'deal_stage_history', ['entered_at'], unique=False)
    op.create_table('email_clicks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['email_recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_clicks_clicked_at', 'email_clicks', ['clicked_at'], unique=False)
    op.create_index('ix_email_clicks_recipient_id', 'email_clicks', ['recipient_id'], unique=False)
    op.create_table('social_message_replies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('sent_by', sa.Uuid(), nullable=False),
    sa.Column('platform_reply_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('send_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['social_messages.id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_message_replies_message_id', 'social_message_replies', ['message_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_time', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('custom_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_assignee_id', 'tasks', ['assignee_id'], unique=False)
    op.create_index('ix_tasks_company_id', 'tasks', ['company_id'], unique=False)
    op.create_index('ix_tasks_contact_id', 'tasks', ['contact_id'], unique=False)
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_deal_id', 'tasks', ['deal_id'], unique=False)
    op.create_index('ix_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('ix_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_priority', table_name='tasks')
    op.drop_index('ix_tasks_due_date', table_name='tasks')
    op.drop_index('ix_tasks_deal_id', table_name='tasks')
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_index('ix_tasks_contact_id', table_name='tasks')
    op.drop_index('ix_tasks_company_id', table_name='tasks')
    op.drop_index('ix_tasks_assignee_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_social_message_replies_message_id', table_name='social_message_replies')
    op.drop_table('social_message_replies')
    op.drop_index('ix_email_clicks_recipient_id', table_name='email_clicks')
    op.drop_index('ix_email_clicks_clicked_at', table_name='email_clicks')
    op.drop_table('email_clicks')
    op.drop_index('ix_deal_stage_history_entered_at', table_name='deal_stage_history')
    op.drop_index('ix_deal_stage_history_deal_id', table_name='deal_stage_history')
    op.drop_table('deal_stage_history')
    op.drop_index('ix_activities_type', table_name='activities')
    op.drop_index(op.f('ix_activities_subject'), table_name='activities')
    op.drop_index('ix_activities_owner_id', table_name='activities')
    op.drop_index('ix_activities_deal_id', table_name='activities')
    op.drop_index('ix_activities_created_at', table_name='activities')
    op.drop_index('ix_activities_contact_id', table_name='activities')
    op.drop_index('ix_activities_company_id', table_name='activities')
    op.drop_index('ix_activities_activity_date', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_social_post_analytics_post_id', table_name='social_post_analytics')
    op.drop_table('social_post_analytics')
    op.drop_index('ix_social_messages_thread_id', table_name='social_messages')
    op.drop_index('ix_social_messages_status', table_name='social_messages')
    op.drop_index('ix_social_messages_received_at', table_name='social_messages')
    op.drop_index(op.f('ix_social_messages_platform'), table_name='social_messages')
    op.drop_index('ix_social_messages_message_type', table_name='social_messages')
    op.drop_index('ix_social_messages_account_id', table_name='social_messages')
    op.drop_table('social_messages')
    op.drop_index('ix_social_media_attachments_post_id', table_name='social_media_attachments')
    op.drop_table('social_media_attachments')
    op.drop_index('ix_email_recipients_status', table_name='email_recipients')
    op.drop_index('ix_email_recipients_email', table_name='email_recipients')
    op.drop_index('ix_email_recipients_contact_id', table_name='email_recipients')
    op.drop_index('ix_email_recipients_campaign_id', table_name='email_recipients')
    op.drop_table('email_recipients')
    op.drop_index('ix_email_campaign_metrics_campaign_id', table_name='email_campaign_metrics')
    op.drop_table('email_campaign_metrics')
    op.drop_index('ix_deals_stage_id', table_name='deals')
    op.drop_index('ix_deals_pipeline_id', table_name='deals')
    op.drop_index('ix_deals_owner_id', table_name='deals')
    op.drop_index(op.f('ix_deals_name'), table_name='deals')
    op.drop_index('ix_deals_expected_close_date', table_name='deals')
    op.drop_index('ix_deals_created_at', table_name='deals')
    op.drop_index('ix_deals_contact_id', table_name='deals')
    op.drop_index('ix_deals_company_id', table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_social_posts_status', table_name='social_posts')
    op.drop_index('ix_social_posts_scheduled_at', table_name='social_posts')
    op.drop_index('ix_social_posts_account_id', table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index('ix_pipeline_stages_pipeline_id', table_name='pipeline_stages')
    op.drop_index('ix_pipeline_stages_order', table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index('ix_email_campaigns_status', table_name='email_campaigns')
    op.drop_index('ix_email_campaigns_scheduled_at', table_name='email_campaigns')
    op.drop_index(op.f('ix_email_campaigns_name'), table_name='email_campaigns')
    op.drop_index('ix_email_campaigns_created_by', table_name='email_campaigns')
    op.drop_table('email_campaigns')
    op.drop_index('ix_contacts_status', table_name='contacts')
    op.drop_index('ix_contacts_owner_id', table_name='contacts')
    op.drop_index(op.f('ix_contacts_last_name'), table_name='contacts')
    op.drop_index('ix_contacts_full_name', table_name='contacts')
    op.drop_index(op.f('ix_contacts_first_name'), table_name='contacts')
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.drop_index('ix_contacts_created_at', table_name='contacts')
    op.drop_index('ix_contacts_company_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_social_accounts_platform', table_name='social_accounts')
    op.drop_index('ix_social_accounts_owner_id', table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.drop_index('ix_pipelines_is_default', table_name='pipelines')
    op.drop_index('ix_pipelines_is_active', table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_file_attachments_s3_key'), table_name='file_attachments')
    op.drop_table('file_attachments')
    op.drop_index(op.f('ix_email_templates_name'), table_name='email_templates')
    op.drop_index('ix_email_templates_created_by', table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index('ix_companies_owner_id', table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index('ix_companies_created_at', table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
